Update TdClientImpl.swift
Swiftgram/TDLibKit pull request #29
Opened 2023-03-22 05:38 UTC by k0ry

This changes should prevent SIGABRT after logging out from current session and creating a new one

2023-03-31 02:47 UTC, neoromantic commented
Can this be looked at?

2023-03-31 02:47 UTC, neoromantic approved these changes

2023-04-13 22:36 UTC, Kylmakalle requested changes
Hi @k0ry, can you please bump patch in version file?

2023-04-17 16:08 UTC, Kylmakalle commented
Thanks once again, merged.

2023-04-17 16:08 UTC, closed without merging